// compiler2026-x phase-A (dialect_parse parser split)

#include "Parser.h"
#include "ASTNode.h"
#include "Lexer.h"
#include "Type.h"
#include "TypeContext.h"
#include <cassert>
#include <cstdlib>
#include <cstring>
#include <ostream>
#include <vector>
#include <sstream>

using namespace sys;

ConstValue Parser::dpEarlyFold(ASTNode *node) {
  if (auto ref = dyn_cast<VarRefNode>(node)) {
    if (!symbols.count(ref->name)) {
      dpFail("[dialect-parse] non-constexpr symbol in constant expression: " + ref->name);
    }
    return symbols[ref->name];
  }

  if (auto binary = dyn_cast<BinaryNode>(node)) {
    auto lv = dpEarlyFold(binary->l);
    auto rv = dpEarlyFold(binary->r);
    if (!lv.isFloat && !rv.isFloat) {
      int l = lv.getInt(), r = rv.getInt();
      switch (binary->kind) {
      case BinaryNode::Add:
        return ConstValue(new int(l + r), {});
      case BinaryNode::Sub:
        return ConstValue(new int(l - r), {});
      case BinaryNode::Mul:
        return ConstValue(new int(l * r), {});
      case BinaryNode::Div:
        // Divide by zero might get generated by fuzzer
        return ConstValue(new int(r ? l / r : 0), {});
      case BinaryNode::Mod:
        return ConstValue(new int(r ? l % r : 0), {});
      case BinaryNode::And:
        return ConstValue(new int(l && r), {});
      case BinaryNode::Or:
        return ConstValue(new int(l || r), {});
      case BinaryNode::Eq:
        return ConstValue(new int(l == r), {});
      case BinaryNode::Ne:
        return ConstValue(new int(l != r), {});
      case BinaryNode::Lt:
        return ConstValue(new int(l < r), {});
      case BinaryNode::Le:
        return ConstValue(new int(l <= r), {});
      }
    }
    
    // Implicitly raise to float.
    float l = lv.isFloat ? lv.getFloat() : lv.getInt();
    float r = rv.isFloat ? rv.getFloat() : rv.getInt();
    switch (binary->kind) {
    case BinaryNode::Add:
      return ConstValue(new float(l + r), {});
    case BinaryNode::Sub:
      return ConstValue(new float(l - r), {});
    case BinaryNode::Mul:
      return ConstValue(new float(l * r), {});
    case BinaryNode::Div:
      return ConstValue(new float(l / r), {});
    case BinaryNode::Mod:
      assert(false);
    // Note these relation operations should return int.
    case BinaryNode::And:
      return ConstValue(new int(l && r), {});
    case BinaryNode::Or:
      return ConstValue(new int(l || r), {});
    case BinaryNode::Eq:
      return ConstValue(new int(l == r), {});
    case BinaryNode::Ne:
      return ConstValue(new int(l != r), {});
    case BinaryNode::Lt:
      return ConstValue(new int(l < r), {});
    case BinaryNode::Le:
      return ConstValue(new int(l <= r), {});
    }
  }

  if (auto unary = dyn_cast<UnaryNode>(node)) {
    auto v = dpEarlyFold(unary->node);
    if (v.isFloat) {
      switch (unary->kind) {
      case UnaryNode::Minus:
        return ConstValue(new float(-v.getFloat()), {});
      // Note this should return int.
      case UnaryNode::Not:
        return ConstValue(new int(!v.getFloat()), {});
      default:
        assert(false);
      }
    }

    switch (unary->kind) {
    case UnaryNode::Minus:
      return ConstValue(new int(-v.getInt()), {});
    case UnaryNode::Not:
      return ConstValue(new int(!v.getInt()), {});
    default:
      assert(false);
    }
  }

  if (auto lint = dyn_cast<IntNode>(node))
    return ConstValue(new int(lint->value), {});

  if (auto lfloat = dyn_cast<FloatNode>(node))
    return ConstValue(new float(lfloat->value), {});

  if (auto access = dyn_cast<ArrayAccessNode>(node)) {
    if (!symbols.count(access->array)) {
      std::cerr << "cannot find constant: " << access->array << "\n";
      assert(false);
    }
    auto array = symbols[access->array];
    ConstValue v = array;
    for (auto index : access->indices)
      v = v[dpEarlyFold(index).getInt()];
    return v;
  }

  if (auto arr = dyn_cast<ConstArrayNode>(node))
    return ConstValue(arr->vi, cast<ArrayType>(arr->type)->dims);
  
    if (auto arr = dyn_cast<LocalArrayNode>(node)) {
    // This implies that the whole LocalArray is constant. Try to fold it.
    auto arrTy = cast<ArrayType>(arr->type);
    bool isFloat = isa<FloatType>(arrTy->base);
    if (isFloat) {
      dpFail("[dialect-parse] float local array is not constexpr");
    } else {
      int size = arrTy->getSize();
      int *result = new int[size];
      for (int i = 0; i < size; i++) {
        auto node = arr->va[i];
        if (!node) {
          result[i] = 0;
          continue;
        }

        result[i] = dpEarlyFold(node).getInt();
      }
      return ConstValue(result, arrTy->dims);
    }
  }

  dpFail("[dialect-parse] expression is not constexpr");
}
